# Site settings
title: BIMstandards
description: Sélection des meilleures ressources web sur le BIM et la maquette numérique.
baseurl: ""

# Build settings
markdown: kramdown

collections:
  liens-les-bases:
    output: true
  liens-implementation:
    output: true
  liens-collaboration:
    output: true
  liens-guides:
    output: true
  liens-normalisation:
    output: true
  liens-gestion-patrimoine:
    output: true
  liens-logiciels:
    output: true
