# Site settings
title:            BIMstandards
description:      BIMstandards, ressources pour l'interopérabilité.
baseurl:          ""

# Build settings
markdown:         kramdown
highlighter:      rouge
exclude:          [vendor]
  
# Assets
sass:
  style: compressed
cdn:
  css:            https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
  js:             https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js

# Custom variables
version:          v0.1.0-beta.1
latest_update:    20/03/2016
repo:             https://github.com/bimstandards/bimstandards

# Gems
gems:
  - jekyll-sitemap