# Site settings
title:            BIMstandards
description:      BIMstandards, ressources pour l'interopérabilité.
baseurl:          ""

# Build settings
markdown:         kramdown
highlighter:      pygments

# Custom variables
latest_update:    10/11/2015
repo:             https://github.com/bimstandards/bimstandards

cdn:
  css:            https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
  js:             https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
